### ISSUE TITLE
Can >3M deletions be detected by PAV? 

### ISSUE THREAD

**Issue by yue131** [EichlerLab/pav#42]
Hi, 
 I have two unphased assemblies, both of them have deletion longer than 3M, I intend to use PAV to call variantion, how long the max deletion size discovered by PAV?   Is PAV effective for a deletion longer than 3M?

Thank you very much.

**Comment by paudano** [comment]
PAV supports arbitrarily large DELs as long as the assembly and alignments can capture it cleanly. However, it is detecting very large DELs that might arise from misassemblies between segmental duplications. I'm working on improving PAV's ability to recognize and ignore those DELs without discarding true large DELs. I think I'll have an update for that within a couple of weeks.

If you think the DELs are not real, there is a way to tell PAV to ignore them by flagging potential misassembly sites, but I'm hoping to make PAV better at flagging these on its own.

**Comment by paudano** [comment]
There was a bug that was generating large false deletions, and that's now fixed in 2.3.3. Do you want to try re-running these samples to see if the deletions go away? If not, please let me know. Thanks!

**Comment by paudano** [comment]
I made some additional updates in v2.3.4, it was dropping large insertions. I would re-run that version if you can.

I am actively developing PAV right now, and I am aware that some alignment artifacts still cause large deletions (although the bug fixed in 2.3.3 was a significant improvement). I am addressing these cases. If you see suspicious deletions, please feel free to share so I can continue to improve the pipeline to fit a variety of data.

I did add instructions for applying the misassembly filter in [CONFIG.md](https://github.com/EichlerLab/pav/blob/main/CONFIG.md#misassembly-filter). It can also be used as a temporary work-around until I can improve these alignment-based anomalies, although it's tedious to get all the contig coordinates for deletion breakpoints into BED files.

**Comment by yue131** [comment]
Sorry for the late reply, I will try to use the latest version to detect deletion. If there are any questions, I will give you feedback in time.
